project_id = "cjodbnsjggslngnzwxsv"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/login", "http://127.0.0.1:5173/login", "https://streetpolynews.com", "https://streetpolynews.com/login"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_confirmations = false
enable_signup = true

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_CLIENT_ID)"
secret = "env(GOOGLE_CLIENT_SECRET)"
# The redirect URI should be: http://127.0.0.1:54321/auth/v1/callback

[analytics]
enabled = false
