// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import {
  SUPABASE_ANON_KEY,
  SUPABASE_URL,
  assertCanonicalSupabaseProject,
} from "@/lib/supabase-env";

// Debug environment variables (safe log)
if (import.meta.env.DEV) {
  const currentRef = SUPABASE_URL ? SUPABASE_URL.split(".")[0]?.split("//")[1] : "";
  console.log('Supabase Config:', {
    url: SUPABASE_URL,
    keyLength: SUPABASE_ANON_KEY?.length || 0,
    hasKey: !!SUPABASE_ANON_KEY,
    projectRef: currentRef,
  });
}

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error("Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY.");
}

try {
  assertCanonicalSupabaseProject(SUPABASE_URL, "supabase-client");
} catch (err) {
  console.error("Supabase Project Validation Failed:", err);
  // In DEV, we throw to alert the developer immediately.
  // In PROD, we might choose to log and degrade, but for now we fail safe to prevent data drift.
  if (import.meta.env.DEV || import.meta.env.PROD) {
    throw err;
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  }
});
